### ISSUE TITLE
error on startup, OSX Yosemite

### ISSUE THREAD

**Issue by gvoysey** [georgebrindeiro/scroll-sync#1]
enabling scroll-sync throws 
`Uncaught ReferenceError: stopTracking is not defined` in `~/.atom/packages/scroll-sync/lib/scroll-sync.coffee:76`

Running atom 0.152.0 on OSX 10.10.0

**Comment by mark-hahn** [comment]
I'm sorry for taking two months to respond.  I somehow missed this.  From what I can tell this was fixed.  Let me know if it happens again and i'll reopen.
