### ISSUE TITLE
Uncaught TypeError: Cannot read property  item  of undefined

### ISSUE THREAD

**Issue by JamborJan** [georgebrindeiro/scroll-sync#10]
Enter steps to reproduce below:
1. Open two files you want to compare
2. Put one in each part of the split screen
3. Press `CTRL` + `ALT` + `S`
4. Error occurs, no scrolling possible
5. Press `ESC` and try again
6. Now no error is shown
7. It works kind of but not really, see screen

![untitled](https://cloud.githubusercontent.com/assets/7508960/8964700/6ca42bf2-3627-11e5-8e64-b8b2f1a70919.gif)

**Atom Version**: 1.0.3 **System**: Mac OS X 10.10.4 **Thrown From**:  scroll-sync  https://github.com/mark-hahn/scroll-sync  package, v0.1.4 ### Stack Trace Uncaught TypeError: Cannot read property  item  of undefined     At /Users/JJ/.atom/packages/scroll-sync/lib/scroll-sync.coffee:34 TypeError: Cannot read property  item  of undefined at ScrlSync.startTracking  /Users/JJ/.atom/packages/scroll-sync/lib/scroll-sync.coffee:62:25  at atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle  /Users/JJ/.atom/packages/scroll-sync/lib/scroll-sync.coffee:30:28  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent  /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61 at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22  at HTMLDocument.module.exports.WindowEventHandler.onKeydown  /Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20      ### Commands     -0:00.9.0 scroll-sync:toggle  atom-text-editor.editor.is-focused      ### Config    json { core : {} }     ### Installed Packages    coffee # User scroll-sync, v0.1.4 # Dev No dev packages

**Comment by mark-hahn** [comment]
Damn.  The app isn't working for me at all.  I haven't used it for a while.  I don't have time to do serious debugging right now.  I'll keep this on the top of my list.

**Comment by JamborJan** [comment]
Hey @mark-hahn it is a handy feature, I like it. So take your time and I will wait for it :-)

**Comment by itsdarrylnorris** [comment]
I got this same bug.

Atom Version 1.0.11

Here is my list of packages:

 SFTP-deployment@1.0.2
 atom-autocomplete-php@0.8.5
 atom-beautify@0.28.11
 autoprefixer@3.1.0
 csscomb@0.3.1
 drupal@1.8.0
 drupal-info-file@1.5.1
 editor-stats@0.17.0
 emmet-atom@2.3.12
 file-icons@1.6.9
 git-plus@5.4.7
 javascript-snippets@1.0.0
 linter@1.5.1
 minimap@4.13.3
 recent-projects@0.8.7
 scroll-sync@0.1.4
 term2@0.9.20
 uglify@1.2.4

This looks like it could be a very handy tool.
