### ISSUE TITLE
Jumpy scrolling

### ISSUE THREAD

**Issue by KathrynCrawford** [georgebrindeiro/scroll-sync#13]
Whenever I am using scroll-sync, it seems to only sync every 20 lines or so. So everything does not stay in sync, just somewhat close. It's still working for comparing but it's kinda jarring and makes you have to refocus before you can compare.

![scrollsyncerror](https://cloud.githubusercontent.com/assets/10589544/10350505/ff69025a-6d09-11e5-833b-3f0092f8535b.gif)

**Comment by mark-hahn** [comment]
It cannot sync inside a code section or image.  So the hopping is expected
in the current version.

**Comment by KathrynCrawford** [comment]
Ah, I see. Thanks!
