### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by rugk** [georgebrindeiro/scroll-sync#16]
1. I have two MD files opened in two panes.
2. I press Ctrl+Alt+S.

The two panes do not sync, but the text is shown in the status bar and it also disappears when I click on it. Just sync-scrolling does not work...

No errors are shown in the console.

Atom v1.8.0

**Comment by pzmarzly** [comment]
I have the same issue with 2 XML files

**Comment by rugk** [comment]
@mark-hahn Any news about this issue?

**Comment by vojtech-cerveny** [comment]
+1
Atom version: 1.7.4

**Comment by ondrejProfiq** [comment]
Also not working. 

Atom v1.8.0

**Comment by TPXP** [comment]
This package is also broken on my side. Any update ?

**Comment by mark-hahn** [comment]
I'm afraid that someone else is going to have to step up to the plate and
fix the bugs in my packages.  I've started a company and I have a negative
amount of time available.

Sorry ...

**Comment by TPXP** [comment]
Thank you for the feedback :+1: , I will try to hack this as soon as I have some time. :wink: 

**EDIT :** It seems that the function this module uses to scroll (`TextEditor.scrollToBufferPosition` - https://atom.io/docs/api/v1.9.9/TextEditor#instance-scrollToBufferPosition ) has become quite "lazy" : it will scroll to the line given only if if is not visible, which means that the scrolling is not smooth at all. I will try to use another function, such as the one indicated in this post : https://discuss.atom.io/t/how-can-i-use-the-api-to-scroll-my-current-view-up-and-down/29078/2 .

By the way, it seems there is another issue with the triggers, as the button in the menu does not do anything if we have not yet activated the module previously via the keyboard (`Ctrl+Alt+S`). I will also investigate this.

By the way, thank you for this great opportunity to learn Coffeescript ! :laughing:
