### ISSUE TITLE
Package doesn't seem to work anymore

### ISSUE THREAD

**Issue by ThaoD5** [georgebrindeiro/scroll-sync#20]
The title says it all, I can't get it to work, I installed and activated the tool by pressing CTRL ALT S, the ScrlSync word appears, but my panes arn't synced... maybe have it a go through some tests ? 

Seems a great tool btw, for copy corrections and translations :)

**Comment by mark-hahn** [comment]
I'm sorry, but I have not been able to take time to work on my packages.  I
need someone to take ownership.

**Comment by georgebrindeiro-vtex** [comment]
@ThaoD5 I just took ownership and released version 0.2.3, check it out and see if it works now!
