### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by lukapelc** [georgebrindeiro/scroll-sync#21]
tried and it does not work...

**Comment by kifirkin** [comment]
on windows 7 x64, latest atom, just scrolls slave pane to last line

**Comment by CyberPunkCodes** [comment]
Same on macOS 10.12.4 and Atom 1.16.0. Just flat out doesn't work :(

I hope the dev fixes this.

**Comment by CyberPunkCodes** [comment]
Until they fix the issue, you can get this working yourself.

Mac (terminal): `atom ~/.atom/packages/scroll-sync/lib/scroll-sync.coffee`

That will open the coffee script in Atom for you to easily edit. Then copy the source from the master branch and replace it with what you have: https://github.com/mark-hahn/scroll-sync/blob/master/lib/scroll-sync.coffee

Save the file, relaunch Atom. Scroll Sync works 👍

**Comment by georgebrindeiro-vtex** [comment]
@lukapelc @alexmironof @WadeShuler I just took ownership and released version 0.2.3. Please check it out and see if updating through Atom works now!
