### ISSUE TITLE
panes.length does not return correct number of panes

### ISSUE THREAD

**Issue by georgebrindeiro-vtex** [georgebrindeiro/scroll-sync#26]
In line 40, we attempt to get the number of open panes by calling `panes = atom.workspace.getPanes()` and then checking `panes.length`. 

That does not currently (Atom 1.18.0 ia32) return the correct number of editor panes, however. Testing showed me that the value returned was consistently incremented by 3. No idea what the other three panes returned are, but I am commiting an ugly fix to this for now, by checking for 5 panes instead of 2. 

I would greatly appreciate any light others might be able to shed on this issue.

**Comment by UziTech** [comment]
`atom.workspace.getPanes().length` returns 5 instead of 2 because it includes the 3 dock panes.

if you use `atom.workspace.getCenter().getPanes().length` it should return 2 when there are 2 panes in the main workspace

**Comment by georgebrindeiro-vtex** [comment]
Thanks for the help and explanation. I will close this issue as soon as I test and accept your pull request, later today!
