### ISSUE TITLE
Broken selector?

### ISSUE THREAD

**Issue by arvidboivie** [georgebrindeiro/scroll-sync#3]
Hello!

I couldn't get this to work using the default selector '.workspace .editor :not(.mini)'. Seems the ':not(.mini)' part isn't working correctly.

Added 'scroll-sync:toggle' to '.workspace .editor' in my keymap and it works just fine.

Otherwise exactly what I needed, thanks!

**Comment by mark-hahn** [comment]
Thank you very much.

Fixed in 0.1.1
