### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by X-G** [georgebrindeiro/scroll-sync#9]
The`slave` doesn't scroll until `master` scroll 20 lines.

![aa](https://cloud.githubusercontent.com/assets/6829403/7993689/320b7cc4-0b08-11e5-8ba3-7f896b267437.gif)

**Comment by mark-hahn** [comment]
Do you have images or code sections?  It can't sync inside those.

**Comment by mark-hahn** [comment]
I see from your gif that the problem is in code sections.  This package syncs between markdown and html and there is no html inside a code section.  Atom actually puts a full read-only text editor there.

But thanks for the report.
